# This pipeline is to build anax binaries

name: anax-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the anax-build branch
on:
  push:
    branches: [anax-build]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      GOPATH: /home/runner/work/anax/anax/go
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
           path: go/src/github.com/Al-tekreeti/anax
      
      # prepare the environment
      - name: Set up golang 1.14.1
        uses: actions/setup-go@v2
        with:
           go-version: '1.14.1'

      - name: Install dependencies
        run: |
          sudo usermod -aG sudo $USER
          sudo apt-get update
          go get -u golang.org/x/lint/golint
          sudo npm install -g jshint
          # Docker already installed
          sudo usermod -a -G docker $USER
          newgrp docker
          sudo chown -f -R $USER ~/.docker
          docker version
          # Installing a single node k8s
          echo "Installing k8s"
          sudo snap install microk8s --classic --channel=1.18/stable
          echo "Adding user to k8s group"
          sudo usermod -a -G microk8s $USER
          echo "Creating .kube dir"
          mkdir -p $HOME/.kube
          echo "Making a copy of config into .kube"
          sudo microk8s kubectl config view --raw > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          echo "Changing the ownership of .kube dir"
          sudo chown -f -R $USER $HOME/.kube
          sudo chmod +x $HOME/.kube
          echo "Re-entering the session"
          sudo su - $USER
          sudo chown -R $USER:$USER /var/snap/microk8s/current/credentials
          sudo chown -R $USER:$USER /var/snap/microk8s/current/credentials/client.config
          sudo chmod go+x /var/snap/microk8s/current/credentials
          ls -la /var/snap/microk8s/current/credentials
          echo "Checking the status of k8s"
          sudo microk8s status --wait-ready

      # build anax binaries
      - name: Build anax binaries
        run: cd ${GOPATH}/src/github.com/Al-tekreeti/anax && make

      # E2E development test
      - name: E2E dev-test
        # run: echo $PWD && ls -la
        run: cd ${GOPATH}/src/github.com/Al-tekreeti/anax/test && make test TEST_VARS="NOLOOP=1 PATTERN=sloc"
 
