# This pipeline is to build anax binaries

name: anax-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the anax-build branch
on:
  push:
    branches: [anax-build]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # prepare the environment
      - name: Set up golang 1.14.1
        uses: actions/setup-go@v2
        with:
           go-version: '1.14.1'

      - name: Install dependencies
        run: |
          echo $PATH
          echo $HOME
          echo $PWD
          which go
          go version
          echo $GOPATH
         # sudo apt-get update
         # go get github.com/tools/godep
          # go get -u golang.org/x/lint/golint
          # VAR=$(go list -f {{.Target}} golang.org/x/lint/golint)
          # export PATH=$PATH:$VAR

      # build anax binaries
      # - name: Build anax binaries
      # run: make verbose=y
          
